run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/beeleelee/mall
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - Error return value of .*Close.* is not checked
    - Error return value of .*\.Encode.* is not checked
    - Error return value of .*FlushDB.* is not checked
    - Error return value of `os\.Setenv` is not checked
    - Error return value of `os\.Unsetenv` is not checked
    - Error return value of `msg\.Ack` is not checked
    - Error return value of `cons\.Consume` is not checked
  exclude-files:
    - .*_test\.go$
