apiVersion: v1
kind: Service
metadata:
  name: mall
  namespace: mall
  labels:
    app: mall
spec:
  selector:
    app: mall
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
